from typing import Protocol, runtime_checkable
from fastapi import FastAPI

@runtime_checkable
class Plugin(Protocol):
    name: str
    version: str
    dependencies: list[str]

    def setup(self, app: FastAPI) -> None: ...
    async def before_startup(self) -> None: ...
    async def on_startup(self) -> None: ...
    async def after_startup(self) -> None: ...
    async def on_shutdown(self) -> None: ...